version: "3.3"
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/app
    depends_on:
      - mysql
    links: 
      - mysql
  mysql:
        image: mysql:5.7.20
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: node
            MYSQL_USER: dbadmin
            MYSQL_PASSWORD: 12345
        volumes:
            - "./data:/var/lib/mysql"
        ports: 
            - "3306:3306"